#! /bin/sh

if test -d fw/bin
  then
    PATH="`pwd`/fw/bin:$PATH"
    export PATH
  fi

fwb=`which fw-bootstrap`

if test -z "$fwb"
  then
    echo "bootstrap: fatal: fw-bootstrap not installed or not in PATH" 1>&2
    exit 1
  fi

"$fwb" --fw_version "0.1.35" --revision svn --template C --name glpkerldrv --svn_project_path https://glpkerl.googlecode.com/svn/trunk/glpkerldrv --svn_tag_root https://glpkerl.googlecode.com/svn/tags/glpkerldrv "$@"
